### ISSUE TITLE
Beginning/End of Next Month/Year/...

### ISSUE THREAD

**Issue by phoet** [jinzhu/now#11]
i'm a golang beginner used to rails awesome date-helpers that allow you do stuff like `1.month.ago` or `3.month.from_now`.

in the same sense, i would like to calculate the timestamp of next month. i could not really find a great way to implement this in golang. maybe i just don't know the right tools though. 
calculating it by hand is simple but has a lot of edge cases, so i would like to use it from within a library.

any feedback appreciated.

**Comment by jinzhu** [comment]
refer http://golang.org/pkg/time/#Time.Add

**Comment by phoet** [comment]
this is how i ended up implementing it:

```golang
func EndOfNextMonth() time.Time {
	return calculateEndOfFollowingMonth(time.Now())
}

func calculateEndOfFollowingMonth(t time.Time) time.Time {
	year := t.Year()
	month := t.Month()
	if month == time.December {
		year += 1
		month = time.January
	} else {
		month = time.Month(int(month) + 1)
	}
	tm := time.Date(year, month, 1, 0, 0, 0, 0, time.Now().Location())
	return now.New(tm).EndOfMonth()
}
```

**Comment by jinzhu** [comment]
@phoet it could be `now.EndOfMonth().AddDate(0, 1, 0)`

**Comment by phoet** [comment]
@jinzhu AFAIK this won't yield the expected result. this is from the `AddDate` docs

> AddDate normalizes its result in the same way that Date does, so, for example, adding one month to October 31 yields December 1, the normalized form for November 31.

**Comment by jinzhu** [comment]
I think this should works, although looks tricky ;)

`now.New(time.Now().AddDate(0, 0, 32-t.Day())).EndOfMonth()`

**Comment by phoet** [comment]
because of all this _should_ and _tricky_ i think it would be a great addition to this library.

**Comment by majimboo** [comment]
I second that this should be part of the library.
