### ISSUE TITLE
BeginningOfHour returns incorrect time if TZ is not in a form xx00

### ISSUE THREAD

**Issue by DmitriyMV** [jinzhu/now#18]
Current usage of time.Truncate(time.Hour) will return incorrect time in, for example, America/Caracas TZ. Details: https://github.com/golang/go/issues/16647

**Comment by dc0d** [comment]
It is stated in the documentation of `time.Truncate(...)` too, that the result might have a non-zero minute value.

The implementation could look like (fast hack, I'm not sure):

```
func TruncateHour(t time.Time) (res time.Time) {
	res = t.Truncate(time.Minute * 30)
	if res.Minute() > 0 {
		res = res.Add(-1 * time.Minute).Truncate(time.Minute * 30)
	}
	return
}
```

This affects other functions/methods too (like `BeginningOfDay()`).
