### ISSUE TITLE
Make FirstDayMonday a variable on now.Now struct or a parameter to BeginningOfWeek

### ISSUE THREAD

**Issue by goddardcm** [jinzhu/now#27]
`FirstDayMonday` is currently a package-level variable on the `now` package. I believe it makes more sense for this to be a variable on the `now.Now` struct. Mainly this is because a single application might have different use-cases for `true` vs `false`. However, there are no guarantees that your application (or a library on which you are dependent) won't change the value of the variable without you realizing it. Even setting it right before calling `BeginningOfWeek()` won't guarantee that it gets changed.

Alternatively, since the only use of the variable is in `BeginningOfWeek`, this function could be updated to take in a `bool` parameter to dictate behavior. Likewise, an additional function that mimics `BeginningOfWeek` could be written to specify the desired behavior.

Happy to take care of fixing the issue but want to get some direction before doing so.

**Comment by jinzhu** [comment]
Hello @goddardcm 

Maybe better to use those methods? https://github.com/jinzhu/now#mondaysunday
