### ISSUE TITLE
Unable to parse time without day

### ISSUE THREAD

**Issue by GregorioDiStefano** [jinzhu/now#28]
The README claims the following should work, but, it fails with:

>  panic: Can't parse string as time: 2017-10

```
	t, err := now.Parse("2017-10")

	if err != nil {
		panic(err)
	}
```

Do you need help fixing this? I can contribute a PR.

**Comment by jinzhu** [comment]
Not using latest version?

https://github.com/jinzhu/now/blob/master/now_test.go#L235
