### ISSUE TITLE
(Question) Why don't just use Truncate for BeginningOfDay()

### ISSUE THREAD

**Issue by luebken** [jinzhu/now#3]
I was trying to understand your BeginninfOfDay() code:
https://github.com/jinzhu/now/blob/master/now.go#L17

And I was wandering why don't you just use Truncate:
`t.Truncate(24 * time.Hour)`

**Comment by luebken** [comment]
A running example: http://play.golang.org/p/2HePgjxtcU

**Comment by jinzhu** [comment]
Thank you for your suggestion ;)

**Comment by jinzhu** [comment]
Hi @luebken 

I just reverted the change, because it do cause some issue, https://github.com/jinzhu/now/commit/71e83eef79858ad4cbc7adc384cc6392ba1e5734#commitcomment-9906093

**Comment by luebken** [comment]
Upps. Sorry. I will dig into it once I have some spare time.
