### ISSUE TITLE
WeekStartDay as an attribute of Now type

### ISSUE THREAD

**Issue by rafaeljusto** [jinzhu/now#34]
When using the library we could have different scenarios where the `WeekStartDay` have different values. To avoid concurrence I suggest having a `WeekStartDay` attribute in the `Now` type instead of using as a global variable. For backward compatibility we could keep the global variable as a fallback if the new attribute is not defined.

```go
// WeekStartDay set week start day, default is sunday
var WeekStartDay = time.Sunday

// Now now struct
type Now struct {
	time.Time
	WeekStartDay *time.Weekday
}

// BeginningOfWeek beginning of week
func (now *Now) BeginningOfWeek() time.Time {
	t := now.BeginningOfDay()
	weekday := int(t.Weekday())

	weekStartDay := WeekStartDay
	if now.WeekStartDay != nil {
		weekStartDay = *now.WeekStartDay
	}

	if weekStartDay != time.Sunday {
		weekStartDayInt := int(weekStartDay)

		if weekday < weekStartDayInt {
			weekday = weekday + 7 - weekStartDayInt
		} else {
			weekday = weekday - weekStartDayInt
		}
	}
	return t.AddDate(0, 0, -weekday)
}
```

I could work on a PR if you think this is acceptable.

🤔 The downside is that the type `Now` wouldn't be easy convertible to `time.Time` anymore. And this could break some backward compatibility:

```go
n := now.New(time.Now())
// ...
t1 := time.Time(n) // <-- this will fail now
t2 := n.Time // <-- this will continue working
```

**Comment by Oliver-Fish** [comment]
I'm also happy to work on this fix if @jinzhu would consider merging it.

**Comment by jinzhu** [comment]
Hi @rafaeljusto @Oliver-Fish 

Thank you for your suggestion.

https://github.com/jinzhu/now/commit/262e698960474dec0f38d3015c3350cc3abfcb92
