### ISSUE TITLE
Current quarter

### ISSUE THREAD

**Issue by 030** [jinzhu/now#47]
## Describe the feature

* If the current month is june then quarter number 2 should be returned.
* If july then 3 should be shown. 

## Motivation

We would like to display the quarter in one of our tools.

**Comment by gouguoyin** [comment]
You can try [carbon](https://github.com/golang-module/carbon)
```
fmt.Println(carbon.Parse("2021-06-01").Quarter()) // 2
fmt.Println(carbon.Parse("2021-07-01").Quarter()) // 3
```
