### ISSUE TITLE
Serious error with format "2006-01-02T15:04:05Z" (also see #22)

### ISSUE THREAD

**Issue by lss4** [jinzhu/now#51]
## Reproducible Example

See [this comment](https://github.com/jinzhu/now/issues/22#issuecomment-883815049).

Here's a [playground link](https://play.golang.org/p/vMeofCw2R9v) with more examples demonstrating this issue.

The playground link uses `now.Parse()` and `now.MustParse()`. The return output consists of two parts. 
The first part uses `now.Parse()`, with `time.Now()` as reference.
The second part uses `now.MustParse()`. using the `n` from [your testcase](https://github.com/jinzhu/now/blob/9d6adef43842618d5f0cd184a7710c1968a1d9be/now_test.go#L239) as reference.

Actual playground output (notice the hour and minute):
```
2009-11-10 23:00:00 +0000 UTC m=+0.000000001
2021-07-20 23:59:10 +0000 UTC
2021-07-20 23:00:10 +0000 UTC

2013-11-18 17:51:49.123456789 +0000 UTC
2002-10-12 17:14:56 +0000 UTC
2002-10-12 17:51:56 +0000 UTC
```

The expected playground output should be:
```
2009-11-10 23:00:00 +0000 UTC m=+0.000000001
2021-07-20 00:59:10 +0000 UTC
2021-07-20 00:00:10 +0000 UTC

2013-11-18 17:51:49.123456789 +0000 UTC
2002-10-12 00:14:56 +0000 UTC
2002-10-12 00:00:56 +0000 UTC
```

## Description

When parsing `2006-01-02T15:04:05Z` (`2006-01-02T15:04:05Z07:00` is also affected as tested), the resulted time is incorrect (see the playground output above).
- If the time part is `00:00:00` it works as intended.
- If hour and minute are both `00` but second is nonzero, the current hour and minute (or the hour and minute specified in `n`) will be used instead.
- If hour is `00` but minute is nonzero (second doesn't matter), the current hour will be used instead.

I originally posted about this in the now-closed issue #22 as follow-up, but I'm yet to see any change or fix. As a result, I have switched back to the `time.Parse()` method to process time strings and removed all references to this package (refactored a good amount of code in the progress). A side effect would be that users must now explicitly configure the time format the data use, as `time.Parse()` requires a time format whereas `now.Parse()` does not.

PS: Issue #22 (900383950ad32d94a25bea6105fad9693691f91e) did fix this issue for time format `2006-01-02 15:04:05`, though, as existing test cases (which covered it) are passing.

**Comment by jinzhu** [comment]
Fixed, thank you for your report.
