### ISSUE TITLE
Incorrect time parsed for 00:01

### ISSUE THREAD

**Issue by IvanVolosyuk** [jinzhu/now#6]
The parse uses current hour instead:
2015-06-13 15:01:00 +1000 AEST

**Comment by jinzhu** [comment]
@IvanVolosyuk fixed, thank you for your report.

**Comment by hrvylein** [comment]
Bug is still present. Try to use  MustParse with following timestamp "12.11.2017 - 00:30". Current hour is still parsed instead of 00:30.
